//currentLocation
export const CURRENT_LOCATION = "CURRENT_LOCATION";
export const CURRENT_LIST_CITIES = "CURRENT_LIST_CITIES";
export const CLEAR_CURRENT_LIST_CITIES = "CLEAR_CURRENT_LIST_CITIES";
//searchedLocation
export const SEARCHED_LOCATION = "SEARCHED_LOCATION";
export const SEARCHED_LIST_CITIES = "SEARCHED_LIST_CITIES";
export const CLEAR_SEARCHED_LIST_CITIES = "CLEAR_SEARCHED_LIST_CITIES";

//currentDayForecaste
export const TOTAL_FORECASTE_HOURLY = "TOTAL_FORECASTE_HOURLY";
export const EVENTS_PER_DAY = "EVENTS_PER_DAY";
export const LIST_DAYS_OF_FORECASTE = "NEXT_DAYS_FORECASTE";
export const CAPITAL_CITY_FORECASTE = "CAPITAL_CITY_FORECASTE";

//settings
export const SETTINGS_ITEMS = "SETTINGS_ITEMS";
